---
- name: "Install base packages"
  apt:
    pkg:
      - fail2ban
      - logwatch
      - rsync
      - needrestart
      - aptitude
      - colordiff
- name: "fail2ban local jail"
  template: src=etc/fail2ban/jail.local.j2 dest=/etc/fail2ban/jail.local mode=0644 owner=root group=root
