---
- name: "APT sources"
  template: src=etc/apt/sources.list.j2 dest=/etc/apt/sources.list
  notify:
    - apt-get update
- name: "Installed packages"
  apt:
    pkg:
      - etckeeper
      - sudo
      - fail2ban
      - logwatch
      - rsync
      - needrestart
      - aptitude
      - colordiff
- name: "fail2ban local jail"
  template: src=etc/fail2ban/jail.local.j2 dest=/etc/fail2ban/jail.local mode=0644 owner=root group=root
